unique_ids:
  assets:
    standard-page.html: FU3TITDGVWSUBCQECIGZ2P3JE4JVA46I
    theme.css: SBFABW4H66JQEQ42VXFQUYVUIW6N6PO3
  forms:
    Form1: YHSYNYN5OXTW5NYKGCY6KJBUTQ6WXP6F
  modules: {}
  scripts: {}
  server_modules: {}
